import type { editor } from 'monaco-editor'

export interface PlaygroundTheme {
    id: string
    name: string
    isDark: boolean
    colors: {
        bg: string
        fg: string
        selection: string
        lineHighlight: string
        cursor: string
        gutterBg: string
    }
    tokenColors: editor.ITokenThemeRule[]
}

export const themes: PlaygroundTheme[] = [
    {
        id: 'default-dark',
        name: 'Default Dark',
        isDark: true,
        colors: {
            bg: '#1e1e1e',
            fg: '#d4d4d4',
            selection: '#264f78',
            lineHighlight: '#2a2d2e',
            cursor: '#aeafad',
            gutterBg: '#1e1e1e',
        },
        tokenColors: [
            { token: '', foreground: 'd4d4d4' },
            { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
            { token: 'keyword', foreground: '569cd6' },
            { token: 'keyword.control', foreground: 'c586c0' },
            { token: 'string', foreground: 'ce9178' },
            { token: 'string.escape', foreground: 'd7ba7d' },
            { token: 'number', foreground: 'b5cea8' },
            { token: 'regexp', foreground: 'd16969' },
            { token: 'type', foreground: '4ec9b0' },
            { token: 'type.identifier', foreground: '4ec9b0' },
            { token: 'class', foreground: '4ec9b0' },
            { token: 'function', foreground: 'dcdcaa' },
            { token: 'variable', foreground: '9cdcfe' },
            { token: 'variable.predefined', foreground: '4fc1ff' },
            { token: 'constant', foreground: '4fc1ff' },
            { token: 'operator', foreground: 'd4d4d4' },
            { token: 'delimiter', foreground: 'd4d4d4' },
            { token: 'delimiter.bracket', foreground: 'ffd700' },
            { token: 'tag', foreground: '569cd6' },
            { token: 'attribute.name', foreground: '9cdcfe' },
            { token: 'attribute.value', foreground: 'ce9178' },
            { token: 'metatag', foreground: '569cd6' },
            { token: 'metatag.content', foreground: 'ce9178' },
            { token: 'annotation', foreground: 'dcdcaa' },
            { token: 'key', foreground: '9cdcfe' },
        ],
    },
    {
        id: 'default-light',
        name: 'Default Light',
        isDark: false,
        colors: {
            bg: '#ffffff',
            fg: '#000000',
            selection: '#add6ff',
            lineHighlight: '#f5f5f5',
            cursor: '#000000',
            gutterBg: '#ffffff',
        },
        tokenColors: [
            { token: '', foreground: '000000' },
            { token: 'comment', foreground: '008000', fontStyle: 'italic' },
            { token: 'keyword', foreground: '0000ff' },
            { token: 'keyword.control', foreground: 'af00db' },
            { token: 'string', foreground: 'a31515' },
            { token: 'string.escape', foreground: '795e26' },
            { token: 'number', foreground: '098658' },
            { token: 'regexp', foreground: '811f3f' },
            { token: 'type', foreground: '267f99' },
            { token: 'type.identifier', foreground: '267f99' },
            { token: 'class', foreground: '267f99' },
            { token: 'function', foreground: '795e26' },
            { token: 'variable', foreground: '001080' },
            { token: 'variable.predefined', foreground: '0070c1' },
            { token: 'constant', foreground: '0070c1' },
            { token: 'operator', foreground: '000000' },
            { token: 'delimiter', foreground: '000000' },
            { token: 'delimiter.bracket', foreground: '795e26' },
            { token: 'tag', foreground: '800000' },
            { token: 'attribute.name', foreground: 'ff0000' },
            { token: 'attribute.value', foreground: '0000ff' },
            { token: 'metatag', foreground: '800000' },
            { token: 'metatag.content', foreground: '0000ff' },
            { token: 'annotation', foreground: '795e26' },
            { token: 'key', foreground: '001080' },
        ],
    },
    {
        id: 'monokai',
        name: 'Monokai',
        isDark: true,
        colors: {
            bg: '#272822',
            fg: '#f8f8f2',
            selection: '#49483e',
            lineHighlight: '#3e3d32',
            cursor: '#f8f8f0',
            gutterBg: '#272822',
        },
        tokenColors: [
            { token: '', foreground: 'f8f8f2' },
            { token: 'comment', foreground: '75715e', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'f92672' },
            { token: 'keyword.control', foreground: 'f92672' },
            { token: 'string', foreground: 'e6db74' },
            { token: 'string.escape', foreground: 'ae81ff' },
            { token: 'number', foreground: 'ae81ff' },
            { token: 'regexp', foreground: 'e6db74' },
            { token: 'type', foreground: '66d9ef', fontStyle: 'italic' },
            { token: 'type.identifier', foreground: 'a6e22e' },
            { token: 'class', foreground: 'a6e22e' },
            { token: 'function', foreground: 'a6e22e' },
            { token: 'variable', foreground: 'f8f8f2' },
            { token: 'variable.predefined', foreground: '66d9ef' },
            { token: 'constant', foreground: 'ae81ff' },
            { token: 'operator', foreground: 'f92672' },
            { token: 'delimiter', foreground: 'f8f8f2' },
            { token: 'delimiter.bracket', foreground: 'f8f8f2' },
            { token: 'tag', foreground: 'f92672' },
            { token: 'attribute.name', foreground: 'a6e22e' },
            { token: 'attribute.value', foreground: 'e6db74' },
            { token: 'metatag', foreground: 'f92672' },
            { token: 'metatag.content', foreground: 'e6db74' },
            { token: 'annotation', foreground: 'a6e22e' },
            { token: 'key', foreground: 'f92672' },
        ],
    },
    {
        id: 'dracula',
        name: 'Dracula',
        isDark: true,
        colors: {
            bg: '#282a36',
            fg: '#f8f8f2',
            selection: '#44475a',
            lineHighlight: '#44475a',
            cursor: '#f8f8f2',
            gutterBg: '#282a36',
        },
        tokenColors: [
            { token: '', foreground: 'f8f8f2' },
            { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'ff79c6' },
            { token: 'keyword.control', foreground: 'ff79c6' },
            { token: 'string', foreground: 'f1fa8c' },
            { token: 'string.escape', foreground: 'bd93f9' },
            { token: 'number', foreground: 'bd93f9' },
            { token: 'regexp', foreground: 'f1fa8c' },
            { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
            { token: 'type.identifier', foreground: '8be9fd' },
            { token: 'class', foreground: '8be9fd' },
            { token: 'function', foreground: '50fa7b' },
            { token: 'variable', foreground: 'f8f8f2' },
            { token: 'variable.predefined', foreground: '8be9fd' },
            { token: 'constant', foreground: 'bd93f9' },
            { token: 'operator', foreground: 'ff79c6' },
            { token: 'delimiter', foreground: 'f8f8f2' },
            { token: 'delimiter.bracket', foreground: 'f8f8f2' },
            { token: 'tag', foreground: 'ff79c6' },
            { token: 'attribute.name', foreground: '50fa7b' },
            { token: 'attribute.value', foreground: 'f1fa8c' },
            { token: 'metatag', foreground: 'ff79c6' },
            { token: 'metatag.content', foreground: 'f1fa8c' },
            { token: 'annotation', foreground: '50fa7b' },
            { token: 'key', foreground: 'ff79c6' },
        ],
    },
    {
        id: 'one-dark',
        name: 'One Dark Pro',
        isDark: true,
        colors: {
            bg: '#282c34',
            fg: 'abb2bf',
            selection: '#3e4451',
            lineHighlight: '#2c313c',
            cursor: '528bff',
            gutterBg: '#282c34',
        },
        tokenColors: [
            { token: '', foreground: 'abb2bf' },
            { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'c678dd' },
            { token: 'keyword.control', foreground: 'c678dd' },
            { token: 'string', foreground: '98c379' },
            { token: 'string.escape', foreground: '56b6c2' },
            { token: 'number', foreground: 'd19a66' },
            { token: 'regexp', foreground: '98c379' },
            { token: 'type', foreground: 'e5c07b' },
            { token: 'type.identifier', foreground: 'e5c07b' },
            { token: 'class', foreground: 'e5c07b' },
            { token: 'function', foreground: '61afef' },
            { token: 'variable', foreground: 'e06c75' },
            { token: 'variable.predefined', foreground: 'd19a66' },
            { token: 'constant', foreground: 'd19a66' },
            { token: 'operator', foreground: '56b6c2' },
            { token: 'delimiter', foreground: 'abb2bf' },
            { token: 'delimiter.bracket', foreground: 'abb2bf' },
            { token: 'tag', foreground: 'e06c75' },
            { token: 'attribute.name', foreground: 'd19a66' },
            { token: 'attribute.value', foreground: '98c379' },
            { token: 'metatag', foreground: 'e06c75' },
            { token: 'metatag.content', foreground: '98c379' },
            { token: 'annotation', foreground: '61afef' },
            { token: 'key', foreground: 'e06c75' },
        ],
    },
    {
        id: 'github-dark',
        name: 'GitHub Dark',
        isDark: true,
        colors: {
            bg: '#0d1117',
            fg: '#c9d1d9',
            selection: '#1f3a5f',
            lineHighlight: '#161b22',
            cursor: '#c9d1d9',
            gutterBg: '#0d1117',
        },
        tokenColors: [
            { token: '', foreground: 'c9d1d9' },
            { token: 'comment', foreground: '8b949e', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'ff7b72' },
            { token: 'keyword.control', foreground: 'ff7b72' },
            { token: 'string', foreground: 'a5d6ff' },
            { token: 'string.escape', foreground: '79c0ff' },
            { token: 'number', foreground: '79c0ff' },
            { token: 'regexp', foreground: 'a5d6ff' },
            { token: 'type', foreground: 'ffa657' },
            { token: 'type.identifier', foreground: 'ffa657' },
            { token: 'class', foreground: 'ffa657' },
            { token: 'function', foreground: 'd2a8ff' },
            { token: 'variable', foreground: 'c9d1d9' },
            { token: 'variable.predefined', foreground: '79c0ff' },
            { token: 'constant', foreground: '79c0ff' },
            { token: 'operator', foreground: 'ff7b72' },
            { token: 'delimiter', foreground: 'c9d1d9' },
            { token: 'delimiter.bracket', foreground: 'c9d1d9' },
            { token: 'tag', foreground: '7ee787' },
            { token: 'attribute.name', foreground: '79c0ff' },
            { token: 'attribute.value', foreground: 'a5d6ff' },
            { token: 'metatag', foreground: '7ee787' },
            { token: 'metatag.content', foreground: 'a5d6ff' },
            { token: 'annotation', foreground: 'd2a8ff' },
            { token: 'key', foreground: '79c0ff' },
        ],
    },
    {
        id: 'nord',
        name: 'Nord',
        isDark: true,
        colors: {
            bg: '#2e3440',
            fg: 'd8dee9',
            selection: '#434c5e',
            lineHighlight: '#3b4252',
            cursor: 'd8dee9',
            gutterBg: '#2e3440',
        },
        tokenColors: [
            { token: '', foreground: 'd8dee9' },
            { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
            { token: 'keyword', foreground: '81a1c1' },
            { token: 'keyword.control', foreground: '81a1c1' },
            { token: 'string', foreground: 'a3be8c' },
            { token: 'string.escape', foreground: 'ebcb8b' },
            { token: 'number', foreground: 'b48ead' },
            { token: 'regexp', foreground: 'ebcb8b' },
            { token: 'type', foreground: '8fbcbb' },
            { token: 'type.identifier', foreground: '8fbcbb' },
            { token: 'class', foreground: '8fbcbb' },
            { token: 'function', foreground: '88c0d0' },
            { token: 'variable', foreground: 'd8dee9' },
            { token: 'variable.predefined', foreground: '81a1c1' },
            { token: 'constant', foreground: 'b48ead' },
            { token: 'operator', foreground: '81a1c1' },
            { token: 'delimiter', foreground: 'eceff4' },
            { token: 'delimiter.bracket', foreground: 'eceff4' },
            { token: 'tag', foreground: '81a1c1' },
            { token: 'attribute.name', foreground: '8fbcbb' },
            { token: 'attribute.value', foreground: 'a3be8c' },
            { token: 'metatag', foreground: '81a1c1' },
            { token: 'metatag.content', foreground: 'a3be8c' },
            { token: 'annotation', foreground: '88c0d0' },
            { token: 'key', foreground: '81a1c1' },
        ],
    },
    {
        id: 'solarized-dark',
        name: 'Solarized Dark',
        isDark: true,
        colors: {
            bg: '#002b36',
            fg: '#839496',
            selection: '#073642',
            lineHighlight: '#073642',
            cursor: '#839496',
            gutterBg: '#002b36',
        },
        tokenColors: [
            { token: '', foreground: '839496' },
            { token: 'comment', foreground: '586e75', fontStyle: 'italic' },
            { token: 'keyword', foreground: '859900' },
            { token: 'keyword.control', foreground: '859900' },
            { token: 'string', foreground: '2aa198' },
            { token: 'string.escape', foreground: 'cb4b16' },
            { token: 'number', foreground: 'd33682' },
            { token: 'regexp', foreground: 'd33682' },
            { token: 'type', foreground: 'b58900' },
            { token: 'type.identifier', foreground: 'b58900' },
            { token: 'class', foreground: 'b58900' },
            { token: 'function', foreground: '268bd2' },
            { token: 'variable', foreground: '839496' },
            { token: 'variable.predefined', foreground: 'cb4b16' },
            { token: 'constant', foreground: 'd33682' },
            { token: 'operator', foreground: '859900' },
            { token: 'delimiter', foreground: '839496' },
            { token: 'delimiter.bracket', foreground: '93a1a1' },
            { token: 'tag', foreground: '268bd2' },
            { token: 'attribute.name', foreground: '93a1a1' },
            { token: 'attribute.value', foreground: '2aa198' },
            { token: 'metatag', foreground: '268bd2' },
            { token: 'metatag.content', foreground: '2aa198' },
            { token: 'annotation', foreground: '268bd2' },
            { token: 'key', foreground: '268bd2' },
        ],
    },
    {
        id: 'cobalt2',
        name: 'Cobalt2',
        isDark: true,
        colors: {
            bg: '#132734',
            fg: '#ffffff',
            selection: '#0050a4',
            lineHighlight: '#193548',
            cursor: 'fff',
            gutterBg: '#132734',
        },
        tokenColors: [
            { token: '', foreground: 'ffffff' },
            { token: 'comment', foreground: '5c5f66', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'ffc600' },
            { token: 'keyword.control', foreground: 'ffc600' },
            { token: 'string', foreground: '7ec699' },
            { token: 'string.escape', foreground: '9c27b0' },
            { token: 'number', foreground: 'ff9d00' },
            { token: 'regexp', foreground: 'ff9d00' },
            { token: 'type', foreground: 'ff9d00' },
            { token: 'type.identifier', foreground: 'ffcb6b' },
            { token: 'class', foreground: 'ffcb6b' },
            { token: 'function', foreground: '82aaff' },
            { token: 'variable', foreground: 'ffffff' },
            { token: 'variable.predefined', foreground: 'ff5572' },
            { token: 'constant', foreground: 'f07178' },
            { token: 'operator', foreground: 'ff9d00' },
            { token: 'delimiter', foreground: 'ffffff' },
            { token: 'delimiter.bracket', foreground: 'ffffff' },
            { token: 'tag', foreground: 'ff9d00' },
            { token: 'attribute.name', foreground: 'ffcb6b' },
            { token: 'attribute.value', foreground: '7ec699' },
            { token: 'metatag', foreground: 'ff9d00' },
            { token: 'metatag.content', foreground: '7ec699' },
            { token: 'annotation', foreground: '82aaff' },
            { token: 'key', foreground: '82aaff' },
        ],
    },
    {
        id: 'synthwave87',
        name: "SynthWave '87",
        isDark: true,
        colors: {
            bg: '#241b30',
            fg: '#ffffff',
            selection: '#423958',
            lineHighlight: '#2d2140',
            cursor: '#ffffff',
            gutterBg: '#241b30',
        },
        tokenColors: [
            { token: '', foreground: 'ffffff' },
            { token: 'comment', foreground: '848bb8', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'fede06' },
            { token: 'keyword.control', foreground: 'f97e72' },
            { token: 'string', foreground: 'ff8b39' },
            { token: 'string.escape', foreground: '36f9f6' },
            { token: 'number', foreground: 'f97e72' },
            { token: 'regexp', foreground: 'f97e72' },
            { token: 'type', foreground: 'fe4450', fontStyle: 'italic' },
            { token: 'type.identifier', foreground: 'fe4450' },
            { token: 'class', foreground: 'fe4450' },
            { token: 'function', foreground: '36f9f6' },
            { token: 'variable', foreground: 'ffffff' },
            { token: 'variable.predefined', foreground: '36f9f6' },
            { token: 'constant', foreground: 'fe4450' },
            { token: 'operator', foreground: 'f97e72' },
            { token: 'delimiter', foreground: 'fede06' },
            { token: 'delimiter.bracket', foreground: 'fede06' },
            { token: 'tag', foreground: 'f97e72' },
            { token: 'attribute.name', foreground: '36f9f6' },
            { token: 'attribute.value', foreground: 'ff8b39' },
            { token: 'metatag', foreground: 'f97e72' },
            { token: 'metatag.content', foreground: 'ff8b39' },
            { token: 'annotation', foreground: '36f9f6' },
            { token: 'key', foreground: '36f9f6' },
        ],
    },
]

export const getThemeById = (id: string): PlaygroundTheme | undefined => {
    return themes.find(t => t.id === id)
}
